### ISSUE TITLE
Deleted code

### ISSUE THREAD

**Issue by hakip** [omn0mn0m/Mion#29]
I used it to parse my old september, after choosing new and update, it regress my post to default code state.
Without even an option to undo, now my post is like this
https://anilist.co/forum/thread/16404/comment/405156

**Comment by omn0mn0m** [comment]
Looking at your old challenge posts, it looks like you modify the example format posted on Google Docs a bit. Since there was no guideline for the old format on what can and can't be modified, I didn't account for any modifications in my parser. I'm sorry, and I hope you backed up your post somewhere to revert it.

**Comment by hakip** [comment]
I didn't lol
But using the app I was able to re-create it in a short time, so it's not a problem now.
Very cool app, will make use of it for my next challenges lol
